"""Write the sewn logo from src/stitches/icon.svg as Android vector drawables.

Vector drawables take SVG path data verbatim but have no stroke-dasharray, so
the stitches (the thread's 9-on 6-off, the border's 6-on 4.5-off) are cut
here into one short path per stitch, each a polyline along the curve. Run it
after editing icon.svg:

    python3 android/tools/make_logo.py

Output (committed, so a build needs nothing but Gradle):
  res/drawable/logo.xml                  the whole tile: the dock's Home
                                         button, and the launcher icon below
                                         API 26 via mipmap-anydpi/ic_launcher
  res/drawable/ic_launcher_foreground.xml  seam and thread only, for the
                                         adaptive icon (its mask would cut the
                                         square border stitch at the corners)
"""

import math
from pathlib import Path

RES = Path(__file__).resolve().parent.parent / "app" / "src" / "main" / "res"
THREAD = (  # icon.svg's two thread paths, as cubic segments
    (((22, 78), (34, 50), (38, 38), (50, 20)), ((50, 20), (62, 38), (66, 50), (78, 78))),
    (((22, 22), (34, 50), (38, 62), (50, 80)), ((50, 80), (62, 62), (66, 50), (78, 22))),
)
SEAM = "M 22,78 C 34,50 38,38 50,20 C 62,38 66,50 78,78 M 22,22 C 34,50 38,62 50,80 C 62,62 66,50 78,22"
TILE = "M18,0 L82,0 A18,18 0 0 1 100,18 L100,82 A18,18 0 0 1 82,100 L18,100 A18,18 0 0 1 0,82 L0,18 A18,18 0 0 1 18,0 Z"
BORDER = (7, 7, 86, 12)  # the <rect> x, y, size and rx of the running stitch
STEP = 0.05  # sampling distance along a curve, in SVG units


def cubic(p0, p1, p2, p3, t):
    u = 1 - t
    return tuple(u ** 3 * a + 3 * u * u * t * b + 3 * u * t * t * c + t ** 3 * d for a, b, c, d in zip(p0, p1, p2, p3))


def thread_points(segments):
    return [cubic(*seg, i / 2000) for seg in segments for i in range(2001)]


def border_points():
    """The rounded rect, clockwise from the top-left corner's end, as SVG draws a <rect>."""
    x, y, size, r = BORDER
    centres = ((x + size - r, y + r), (x + size - r, y + size - r), (x + r, y + size - r), (x + r, y + r))
    points = [(x + r, y)]
    for k, (cx, cy) in enumerate(centres):
        points += [(cx + r * math.cos(math.radians(k * 90 - 90 + a / 10)),
                    cy + r * math.sin(math.radians(k * 90 - 90 + a / 10))) for a in range(901)]
    return points


def dashes(points, on, off):
    """Cut a polyline into dashes, starting with a dash at its start, as SVG does."""
    dense = [points[0]]
    for a, b in zip(points, points[1:]):
        n = max(1, math.ceil(math.dist(a, b) / STEP))
        dense += [(a[0] + (b[0] - a[0]) * i / n, a[1] + (b[1] - a[1]) * i / n) for i in range(1, n + 1)]
    runs, run, length = [], [], 0.0
    for prev, p in zip(dense[:1] + dense, dense):
        length += math.dist(prev, p)
        if length % (on + off) <= on:
            run.append(p)
        elif run:
            runs.append(run)
            run = []
    return [r for r in runs + [run] if len(r) > 1]


def simplify(points, eps=0.02):
    """Ramer-Douglas-Peucker: a straight stitch keeps its two ends, a curved one a few points."""
    if len(points) < 3:
        return points
    (x0, y0), (x1, y1) = points[0], points[-1]
    span = math.dist(points[0], points[-1]) or 1e-9
    far, index = max((abs((y1 - y0) * px - (x1 - x0) * py + x1 * y0 - y1 * x0) / span, i)
                     for i, (px, py) in enumerate(points[1:-1], 1))
    if far < eps:
        return [points[0], points[-1]]
    return simplify(points[:index + 1], eps)[:-1] + simplify(points[index:], eps)


def path_data(runs):
    num = lambda v: f"{v:.2f}".rstrip("0").rstrip(".")
    return " ".join("M" + " L".join(f"{num(x)},{num(y)}" for x, y in simplify(run)) for run in runs)


def path(data, **attrs):
    extra = "".join(f'\n        android:{k}="{v}"' for k, v in attrs.items())
    return f'    <path\n        android:pathData="{data}"{extra} />\n'


def vector(size, viewport, body, comment):
    return (f'<?xml version="1.0" encoding="utf-8"?>\n<!-- {comment} Generated by android/tools/make_logo.py'
            f' from src/stitches/icon.svg; edit that and rerun. -->\n'
            f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size}dp"\n    android:height="{size}dp"\n'
            f'    android:viewportWidth="{viewport}"\n    android:viewportHeight="{viewport}">\n{body}</vector>\n')


def main():
    thread = path_data([run for segments in THREAD for run in dashes(thread_points(segments), 9, 6)])
    seam = path(SEAM, strokeColor="#4B5563", strokeWidth="2")
    stitches = path(thread, strokeColor="#E5E7EB", strokeWidth="6")
    tile = (path(TILE, fillColor="#1F2937")
            + path(path_data(dashes(border_points(), 6, 4.5)), strokeColor="#6B7280", strokeWidth="3")
            + seam + stitches)
    (RES / "drawable" / "logo.xml").write_text(vector(48, 100, tile, "The sewn logo, whole."))
    # The group scales the 100x100 viewBox into the 108x108 adaptive canvas, centred.
    group = ('    <group android:scaleX="1.035" android:scaleY="1.035" android:translateX="2.25" '
             'android:translateY="2.25">\n' + "".join("    " + line + "\n" for line in (seam + stitches).splitlines())
             + "    </group>\n")
    (RES / "drawable" / "ic_launcher_foreground.xml").write_text(
        vector(108, 108, group, "The adaptive icon's foreground: seam and thread, no border."))


if __name__ == "__main__":
    main()
